os: windows

language: shell

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

script:
- echo %TRAVIS_BUILD_DIR%

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep_history: false
#   on:
#     branch: main